FROM node:11.6.0-alpine

WORKDIR '/app'

RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*

COPY package.json yarn.lock /app/

COPY . ./
RUN yarn global add react-scripts
RUN yarn install
RUN yarn run build

# production environment

FROM nginx:1.13.9-alpine

# ARG app_name

RUN rm -rf /etc/nginx/conf.d

COPY conf /etc/nginx

COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
