FROM node:11.6.0-alpine
WORKDIR '/app'
# Install yarn and other dependencies via apk
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*
COPY package.json yarn.lock /app/
COPY . ./
RUN yarn install
RUN yarn global add react-scripts
COPY . ./
CMD ["npm", "run", "start"]
