import { getUUID } from "./commonFunctions";

export const DELETE_ALL_INSTANCES = 'DELETE_ALL_INSTANCES';
export const DELETE_INSTANCE = 'DELETE_INSTANCE';
export const SAVE_ALL_INSTANCES = 'SAVE_ALL_INSTANCES';
export const SAVE_INSTANCE = 'SAVE_INSTANCE';
export const SAVE_LAST = 'SAVE_LAST';
export const INVALID_INSTANCE_CANNOT_SAVE = 'INVALID_INSTANCE_CANNOT_SAVE';

export const HTTP_STANDERD_ERRORS = {
  400: 'Bad request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not Found',
  408: 'Request time out',
  413: 'Payload to large',
  414: 'URL to long',
  415: 'Unsupported media type',
  500: 'Internal server error',
  501: 'Not implimented',
  502: 'Bad gateway',
  503: 'Service unavailable',
  504: 'Gateway timeout',
};

export const DATA = [
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Toyota',
    model: 'Celica',
    price: 35000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Ford',
    model: 'Mondeo',
    price: 32000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
  {
    id: getUUID(),
    make: 'Porsche',
    model: 'Boxter',
    price: 72000,
    view: '12',
    edit: '123123',
    delete: 'asd',
  },
];
